import type { VercelRequest, VercelResponse } from '@vercel/node'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export default async function handler(
  req: VercelRequest,
  res: VercelResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  const { encounter_id } = req.body

  if (!encounter_id) {
    return res.status(400).json({ error: 'encounter_id is required' })
  }

  try {
    // Get encounter data
    const { data: encounter, error: encounterError } = await supabase
      .from('encounters')
      .select('*, patients(*), users(*)')
      .eq('id', encounter_id)
      .single()

    if (encounterError || !encounter) {
      throw new Error('Encounter not found')
    }

    // Generate PDF HTML
    const html = generatePDFHTML(encounter)

    // For MVP, return HTML that can be printed/saved as PDF
    // In production, use a library like puppeteer or pdfkit
    return res.status(200).json({
      html,
      filename: `encounter-${encounter.id.substring(0, 8)}.pdf`,
    })
  } catch (error: any) {
    console.error('PDF export error:', error)
    return res.status(500).json({
      error: error.message || 'Failed to generate PDF',
    })
  }
}

function generatePDFHTML(encounter: any): string {
  const patient = encounter.patients
  const provider = encounter.users
  const soap = encounter.soap_note || {}

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Encounter Note - ${encounter.id.substring(0, 8)}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
    h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
    h2 { color: #555; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
    .header { margin-bottom: 30px; }
    .info-row { margin: 10px 0; }
    .label { font-weight: bold; display: inline-block; width: 150px; }
    .soap-section { margin: 20px 0; }
    .soap-content { margin-left: 20px; white-space: pre-wrap; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>Clinical Encounter Note</h1>
    <div class="info-row">
      <span class="label">Date:</span>
      <span>${new Date(encounter.encounter_date).toLocaleDateString()}</span>
    </div>
    <div class="info-row">
      <span class="label">Patient:</span>
      <span>${patient?.first_name} ${patient?.last_name} (DOB: ${patient?.date_of_birth ? new Date(patient.date_of_birth).toLocaleDateString() : 'N/A'})</span>
    </div>
    <div class="info-row">
      <span class="label">Provider:</span>
      <span>${provider?.full_name || 'N/A'}</span>
    </div>
    <div class="info-row">
      <span class="label">Encounter Type:</span>
      <span>${encounter.encounter_type?.replace('_', ' ') || 'N/A'}</span>
    </div>
    ${encounter.chief_complaint ? `<div class="info-row"><span class="label">Chief Complaint:</span><span>${encounter.chief_complaint}</span></div>` : ''}
  </div>

  ${soap.subjective ? `
  <div class="soap-section">
    <h2>Subjective</h2>
    <div class="soap-content">${soap.subjective.hpi || soap.subjective.note || 'N/A'}</div>
  </div>
  ` : ''}

  ${soap.objective ? `
  <div class="soap-section">
    <h2>Objective</h2>
    <div class="soap-content">${soap.objective.physical_exam || soap.objective.note || 'N/A'}</div>
  </div>
  ` : ''}

  ${soap.assessment ? `
  <div class="soap-section">
    <h2>Assessment</h2>
    <div class="soap-content">${soap.assessment.primary_diagnosis || soap.assessment.note || 'N/A'}</div>
    ${encounter.icd10_codes && encounter.icd10_codes.length > 0 ? `
    <div style="margin-top: 10px;">
      <strong>ICD-10 Codes:</strong>
      <ul>
        ${encounter.icd10_codes.map((code: any) => `<li>${code.code} - ${code.description}</li>`).join('')}
      </ul>
    </div>
    ` : ''}
  </div>
  ` : ''}

  ${soap.plan ? `
  <div class="soap-section">
    <h2>Plan</h2>
    <div class="soap-content">${soap.plan.treatment || soap.plan.note || 'N/A'}</div>
  </div>
  ` : ''}

  ${encounter.vitals ? `
  <div class="soap-section">
    <h2>Vital Signs</h2>
    <div class="soap-content">${JSON.stringify(encounter.vitals, null, 2)}</div>
  </div>
  ` : ''}

  <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666;">
    <p>Generated by ScribeMD Pro on ${new Date().toLocaleString()}</p>
    <p>Encounter ID: ${encounter.id}</p>
  </div>
</body>
</html>
  `.trim()
}

